---
- name: vagrrant-dev-env
  hosts: default
  become: yes
  tasks:
  - name: Install Git
    apt:
      name: git
      state: present
      update_cache: yes
  - name: Install vim
    apt:
      name: vim
      state: present
      update_cache: yes
  - name: Install Python
    apt:
      name: python3.8
      state: present
      update_cache: yes
  - name: Install Python
    apt:
      name: python3-pip
      state: present
      update_cache: yes

  - name: Git clone repo
    git:
      repo: "https://github.com/berkguzel/vagrant-flask-dev-env.git"
      dest: "/home/vagrant/vagrant-flask-dev-env.git"
      accept_hostkey: yes
      force: yes
      recursive: no
      version: main
~                       
