apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: 227500/flaskapi
        name: my-image
        ports:
        - containerPort: 3000
        env:
        - name: MYSQL_USERNAME
          value: root
        - name: MYSQL_ROOT_PASSWORD 
          value: "1903"
        - name: MYSQL_PORT_3306_TCP_ADDR
          value: mysql-svc
        - name: MYSQL_PORT_3306_TCP_PORT
          value: "3306"
        - name: MYSQL_INSTANCE_NAME
          value: flaskapp   
